# Generated by Django 4.0.5 on 2022-07-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('question_papers', models.FileField(blank=True, null=True, upload_to='question_papers')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('reading_class', models.CharField(choices=[('eight', 'Eight'), ('nine', 'Nine'), ('ten', 'Ten'), ('eleven', 'Eleven'), ('tweleve', 'Tweleve')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('home_address', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.FileField(null=True, upload_to='student_photos')),
            ],
        ),
    ]
