# Generated by Django 4.0.5 on 2022-07-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('selectClass', models.CharField(max_length=2)),
                ('phNumber', models.CharField(max_length=15)),
                ('homeAddress', models.CharField(max_length=200)),
            ],
        ),
    ]
