# Generated by Django 4.0.5 on 2022-07-06 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dateOfBirth',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
