# Generated by Django 4.0.5 on 2022-07-20 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=10)),
                ('answer_sheet', models.FileField(upload_to='answer_sheets')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdmanage.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdmanage.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdmanage.subject')),
            ],
        ),
    ]
