# Generated by Django 4.0.5 on 2022-07-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage', '0002_student_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dateOfBirth',
        ),
    ]
