# Generated by Django 4.0.5 on 2022-07-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage', '0003_remove_student_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fullName',
            field=models.CharField(max_length=60),
        ),
    ]
