# Generated by Django 4.0.5 on 2022-07-06 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage', '0004_alter_student_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='selectClass',
        ),
    ]
