# Generated by Django 4.0.5 on 2022-07-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage', '0004_readingclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reading_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stdmanage.readingclass'),
        ),
    ]
