# Generated by Django 4.0.5 on 2022-07-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage', '0006_student_selectclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='homeAddress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phNumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='selectClass',
        ),
    ]
