# Generated by Django 4.0.5 on 2022-09-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage', '0009_alter_result_answer_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question_papers',
            field=models.FileField(upload_to='question_papers'),
        ),
    ]
