# Generated by Django 4.0.5 on 2022-07-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage', '0009_student_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='homeAddress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phNumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='selectClass',
        ),
    ]
