# Generated by Django 4.0.5 on 2022-07-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage', '0011_student_dateofbirth_student_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
