# Generated by Django 4.0.5 on 2022-07-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdmanage', '0012_alter_student_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fullName',
        ),
        migrations.RemoveField(
            model_name='student',
            name='homeAddress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phNumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='selectClass',
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='hehehe', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='hehehe2', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='home_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='hehehe3', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='reading_class',
            field=models.CharField(choices=[('eight', 'Eight'), ('nine', 'Nine'), ('ten', 'Ten'), ('eleven', 'Eleven'), ('tweleve', 'Tweleve')], default='hehehe4', max_length=20),
            preserve_default=False,
        ),
    ]
